server:
  port: ${SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  redis:
    host: ${REDIS_SERVER}
    port: ${REDIS_PORT}
  jpa:
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

# spring:
#   profiles:
#     active: dev

# logging:
#   pattern:
#     file: /k8s-log-test
#   file:
#     path: /var/log/test
#   level:
#     root: INFO

# log:
#   config:
#     path: /var/log/test
#     filename: k8s-log-test
    
