server:
  port: 4002

# spring:
#   profiles:
#     active: dev

# logging:
#   pattern:
#     file: /k8s-log-test
#   file:
#     path: /var/log/test
#   level:
#     root: INFO

# log:
#   config:
#     path: /var/log/test
#     filename: k8s-log-test
    
