server:
  port: ${SERVER_PORT:4003}

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  redis:
    host: ${REDIS_SERVER:localhost}
    port: ${REDIS_PORT:6379}
  jpa:
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:sso}
    username: ${DB_USER:sso}
    password: ${DB_PASSWORD:sso}
    driver-class-name: com.mysql.cj.jdbc.Driver
# spring:
#   profiles:
#     active: dev

# logging:
#   pattern:
#     file: /k8s-log-test
#   file:
#     path: /var/log/test
#   level:
#     root: INFO

# log:
#   config:
#     path: /var/log/test
#     filename: k8s-log-test
    
