server:
  port: 4002

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cache:
    type: redis
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  jpa:
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

# spring:
#   profiles:
#     active: dev

# logging:
#   pattern:
#     file: /k8s-log-test
#   file:
#     path: /var/log/test
#   level:
#     root: INFO

# log:
#   config:
#     path: /var/log/test
#     filename: k8s-log-test
    
